name: codevinsky
favicon: null
layout_spectrum: 0.15442
typography_spectrum: 0.65572
title: "808's and line breaks "
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-41145442-18
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.0625
  lightness: 0.125
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
